name: Test SSH Connection

on:
  workflow_dispatch:  # so you can trigger manually

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H your-server-ip >> ~/.ssh/known_hosts

      - name: Run command on server
        run: |
          ssh -i ~/.ssh/id_ed25519 ec2-user@your-server-ip 'echo "GitHub Actions connected successfully!"'
